# Generated by Django 2.2 on 2022-05-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220506_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(default='', max_length=50),
        ),
    ]
