# Generated by Django 2.2 on 2022-05-06 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220506_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='product_slug',
            new_name='slug',
        ),
    ]
